Validate size of signature against algorithm considering JWE
AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet pull request #2008
Opened 2023-01-27 22:20 UTC by brentschmaltz

SymmetricSignatures are now ensuring the size of the signature matches the algorithm.
Authenticated Encryption needed special processing as only the first half of the signature is considered for Aes128CbcHmacSha256, Aes128CbcHmacSha384 and Aes128CbcHmacSha512.

2023-01-27 22:31 UTC, TimHannMSFT commented
Seems like this also addresses #1743, is that correct?

2023-01-27 22:32 UTC, brentschmaltz commented
@TimHannMSFT had not considered #1743

2023-01-27 22:54 UTC, TimHannMSFT commented
My mistake, I think I got the key size check and the signature size check confused.

---
In reply to: [1407145465](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2008#issuecomment-1407145465) [](http://example.com/codeflow?ancestors=1407145465,1407145465)

2023-01-27 23:36 UTC, TimHannMSFT commented on test/Microsoft.IdentityModel.Tokens.Tests/TamperedTokenTests.cs
> +        public async Task JwtSignatureTruncation(ValidateTokenTheoryData theoryData)
>JwtSignatureTruncation [](http://example.com/codeflow?start=26&length=22)

Looks like we're doing some similar testing in SignatureProviderTests::SignatureTrunctation. What's the difference? Looks like that also did symmetric hmac.

Can you help me understand why that didn't catch the issue? Should that test case be updated in any way for protection on the RSA/ECDSA cases?

2023-01-27 23:36 UTC, TimHannMSFT approved these changes
:shipit:

2023-01-29 08:00 UTC, 7409355636 requested changes
Help mail all my checks and money to maggie mccann 1138 rose street portsmouth ohio 45662

2023-01-30 16:33 UTC, brentschmaltz commented on test/Microsoft.IdentityModel.Tokens.Tests/TamperedTokenTests.cs
> +        public async Task JwtSignatureTruncation(ValidateTokenTheoryData theoryData)
@TimHannMSFT internally RSA/ECDSA require the signature bytes to be the correct size, so any truncation will be caught by the .net runtimes.

Signature provider tests missed this because they were being told an incorrect expected size from the JsonWebTokenHandler.

2023-01-30 16:34 UTC, merged