In case take long time to get Metadata
AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet pull request #2041
Opened 2023-03-24 05:34 UTC by RyanLiu99

2023-03-31 17:30 UTC, RyanLiu99 commented
This is to address "stale now" issue.

This meta data is cached for x seconds to reduce the call to Idp server to get meta data.  But to make the cache works, a global lock is imposed cross requests.  Cache start time is set before calling to Id server, not after the call returns. I call it a “stale now”. This is  a problem when call to Idp server take longer then x seconds.  Ocz x seconds has been changes from 30s to 5m from version 6.8 to version 6.27, make it less sever.

When the call to IdentiyProvider has issue, take much longer time, all requests are blocked at this lock. 

Once the call eventually returned from Idp server, SOME requests piling at the lock can just take cached data and  keep going. But if the call to Id server take longer than cache time x seconds, those requests come later than stale now + x seconds, still need call Id server again. The global lock is blocking 2nd half requests and new requests again.  This can get worse and worse.

2023-04-14 21:07 UTC, brentschmaltz commented on src/Microsoft.IdentityModel.Protocols/Configuration/ConfigurationManager.cs
> +                if (_syncAfter <= DateTimeOffset.UtcNow)
@RyanLiu99 can you removed the local variable "now">

2023-04-14 21:08 UTC, brentschmaltz requested changes
nit: remove local variable: 'now'.

2023-04-17 17:31 UTC, brentschmaltz approved these changes

2023-04-18 17:51 UTC, brentschmaltz commented
@RyanLiu99 for some reason this is showing up with a conflict, can you rebase on top of dev.

2023-04-19 06:14 UTC, RyanLiu99 commented
@brentschmaltz   I just merged dev branch into my branch, no conflicts at all.  Can you try again?

2023-04-20 21:42 UTC, brentschmaltz approved these changes

2023-04-20 21:43 UTC, brentschmaltz commented
@RyanLiu99 something odd is going on, git is blocking this PR.
Perhaps start with a new branch?
Last resort, i can do a manual merge, but would like to see your name on the PR.

2023-04-21 04:55 UTC, RyanLiu99 commented
Ok, @brentschmaltz  I'll do it .

2023-04-25 19:55 UTC, RyanLiu99 commented
A new PR created.  I will close this one.  @brentschmaltz 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2063
Sorry take a while, I was travelling.

2023-04-25 19:55 UTC, closed without merging