Updated Xml.DelegatingXmlReader to support close and ReadContentAsUniqueId
AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet pull request #2116
Opened 2023-06-17 03:07 UTC by MoSelem

Updated Xml.DelegatingXmlReader to delegate to the inner reader: close() and ReadContentAsUniqueId()

2023-06-19 16:21 UTC, MoSelem commented
@microsoft-github-policy-service agree

2023-09-22 19:38 UTC, brentschmaltz approved these changes

2023-09-22 19:52 UTC, trukhanov approved these changes

2023-09-26 18:00 UTC, brentschmaltz commented
@MoSelem you have some conflicts that need to be resolved.

2023-09-26 18:01 UTC, brentschmaltz requested changes
Some conflicts need to be resolved

2023-10-04 17:14 UTC, trukhanov approved these changes

2023-10-06 02:12 UTC, brentschmaltz approved these changes

2023-10-06 02:13 UTC, brentschmaltz commented
@MoSelem Thanks!

2023-10-06 02:13 UTC, merged