Add baseline package validation
AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet pull request #2345
Opened 2023-10-02 23:40 UTC by westin-m

2023-10-03 02:51 UTC, jmprieur requested changes, later dismissed

2023-10-03 02:51 UTC, jmprieur commented on build/common.props
> +    <PackageValidationBaselineVersion>7.0.2</PackageValidationBaselineVersion>
Shouldn't the baseline be 7.0.0? Otherwise how to find breaking changes compared to a major version

2023-10-11 00:00 UTC, keegan-caruso commented on test/Microsoft.IdentityModel.Tokens.Tests/SignatureProviderTests.cs
> +                throw new PlatformNotSupportedException("OSX is excluded as the SignatureTampering test is slow (~6 minutes).");
this doesn't look right, before OSX platforms would skip, now they will fail on this test?

2023-10-11 00:21 UTC, keegan-caruso approved these changes

2023-10-11 01:41 UTC, merged