Fixed bug on case-insensitive properties on OpenIdConnectConfigurationSerializer.cs
AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet pull request #2404
Opened 2023-11-15 15:21 UTC by stvkouvaris

# Bug fix on case-insensitive property deserialization on OpenIdConnectConfigurationSerializer.cs

Fixes #2402

The json reader was getting out of sync after line 289
`string propertyName = JsonPrimitives.ReadPropertyName(ref reader, OpenIdConnectConfiguration.ClassName, true);`
inside the `else` statement that is handling case-insensitive property deserialization.

Removing the `read: true` parameter from all following json property reads, resolves the issue.

2023-11-15 15:23 UTC, stvkouvaris commented
@microsoft-github-policy-service agree

2023-11-15 15:25 UTC, stvkouvaris commented
agree

2023-11-15 15:26 UTC, stvkouvaris commented
@microsoft-github-policy-service agree

2023-11-15 16:59 UTC, keegan-caruso commented
@stvkouvaris would you be willing to add some tests for this?

2024-01-10 13:58 UTC, davek-dev commented
This is causing an issue for me as well, was it supposed to get into yesterday's release?  The PR looks good to me.

2024-01-10 17:46 UTC, jennyf19 commented
> This is causing an issue for me as well, was it supposed to get into yesterday's release? The PR looks good to me.

We need a bit more time to review it @davek-dev and it will go in the 7.2.1 release (end of month or sooner).

2024-01-23 17:20 UTC, jennyf19 reviewed
:shipit:

2024-01-23 17:40 UTC, brentschmaltz commented
Reviewing....

2024-01-23 18:48 UTC, keegan-caruso approved these changes
LGTM

2024-02-04 09:34 UTC, stvkouvaris commented
@jennyf19 I can see that the issue was fixed on 7.3.1 release, however without this pull request getting merged to the main branch. Will it be merged on 7.3.2? Or is this now obsolete?

2024-02-21 17:13 UTC, brentschmaltz commented
@stvkouvaris We had to make a change in the serialization model to ensure that the entire Json Token was read and position the reader on the next token.

This PR (https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2491).
We incorporated your ideas into that PR.

2024-02-21 17:14 UTC, brentschmaltz requested changes
We have used the ideas here in this PR: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2491

And extended the fixes to JsonWebTokens, JsonWebKey and JsonWebKeySet.

2024-02-21 17:14 UTC, brentschmaltz commented
We have used the ideas here in this PR: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2491

And extended the fixes to JsonWebTokens, JsonWebKey and JsonWebKeySet.

2024-02-21 17:14 UTC, closed without merging