Re-factor Issuer Validator to Follow New Validation Model
AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet pull request #2759
Opened 2024-08-01 01:52 UTC by FuPingFranco

# Re-factor Issuer Validator to Follow New Validation Model

## Description

- Removed checks for `ValidIssuer` from Issuer validation.
- Moved away from using `TokenValidationParameters` in favor of the new `ValidationParameters`.
- Added new tests in ValidationParameters class.
- Fixed minor inconsistencies on the code.

2024-08-01 15:17 UTC, iNinja approved these changes, later dismissed
Minor change and we're good.

2024-08-01 15:17 UTC, iNinja commented on src/Microsoft.IdentityModel.Tokens/Validation/Validators.Issuer.cs
> +            if (validationParameters.ValidIssuers.IsNullOrEmpty() && string.IsNullOrWhiteSpace(configuration?.Issuer))
Similar to Brent's comment on the other PR, now that `ValidIssuers` is an `IList`, we should check `.Count == 0`.

2024-08-01 16:48 UTC, brentschmaltz commented on src/Microsoft.IdentityModel.Tokens/Validation/ValidationParameters.cs
> +        private IList<string> _validIssuers = [];
Leave these _validIssuers and _validTokenTypes null.
Use the pattern shown in the Get below.

2024-08-01 16:48 UTC, brentschmaltz commented on src/Microsoft.IdentityModel.Tokens/Validation/ValidationParameters.cs
> +            get { return _validIssuers; }
We should remove the set and use this patern: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/149148109446c4aa6a341cb4d766ec27b5213bdd/src/Microsoft.IdentityModel.Tokens/SecurityTokenDescriptor.cs#L28

2024-08-01 16:53 UTC, brentschmaltz approved these changes

2024-08-01 16:55 UTC, brentschmaltz requested changes, later dismissed
Properties that return IList<T> should not be settable.
If the property can be null, for a successful validation, use a delayed creation.

2024-08-06 09:53 UTC, iNinja commented on src/Microsoft.IdentityModel.Tokens/Validation/Validators.Issuer.cs
> +            if (validationParameters.ValidIssuers.IsNullOrEmpty() && string.IsNullOrWhiteSpace(configuration?.Issuer))
Looks like we are still using `IsNullOrEmpty()` on an `IList`.

The comment above needs to be addressed.

2024-08-06 15:09 UTC, FuPingFranco commented on src/Microsoft.IdentityModel.Tokens/Validation/ValidationParameters.cs
> +            get { return _validIssuers; }
Updated

2024-08-06 15:23 UTC, iNinja approved these changes

2024-08-06 16:38 UTC, SaurabhMSFT approved these changes

2024-08-06 16:46 UTC, merged