Regression testing: Token type, replay, and lifetime validation.
AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet pull request #2823
Opened 2024-09-11 15:22 UTC by iNinja

# Regression testing: Token type, replay, and lifetime validation.

- Updated theory, added new test cases.
 
Part of #2711

2024-09-11 15:28 UTC, keegan-caruso commented on test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerValidationParametersTests.cs
> +            public TestTokenReplayCache(bool onAddReturnValue, bool onFindReturnValue)
```suggestion

            public TestTokenReplayCache(bool onAddReturnValue, bool onFindReturnValue)
```

2024-09-11 15:28 UTC, keegan-caruso commented on test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerValidationParametersTests.cs
> +            public bool TryAdd(string securityToken, DateTime expirationTime)
```suggestion

            public bool TryAdd(string securityToken, DateTime expirationTime)
```

2024-09-11 15:29 UTC, keegan-caruso approved these changes
Few spacing issues, otherwise LGTM

2024-09-11 16:24 UTC, brentschmaltz commented on test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerValidationParametersTests.cs
> +
be consistent with spacing around #nullable.
Other files do not have a blank line.

2024-09-11 16:27 UTC, brentschmaltz commented on test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerValidationParametersTests.cs
> +                    new JsonWebTokenHandlerValidationParametersTheoryData("Invalid_ValidationParametersNull")
add a new line between creation of theoryData.

2024-09-11 16:30 UTC, brentschmaltz commented on test/Microsoft.IdentityModel.JsonWebTokens.Tests/JsonWebTokenHandlerValidationParametersTests.cs
> +            jsonWebTokenHandler.SetDefaultTimesOnTokenCreation = theoryData.SetDefaultValuesOnTokenCreation;
Why do we not create the jwt when creating the theoryData?

2024-09-11 16:36 UTC, brentschmaltz commented
If the goal of this test is to check that the path with TokenValidationParameters is the same as ValidationParameters, the number of tests will be large.

I would suggest having separate files for each validation step.
In this way we will be able to focus on one validation step at time.
This separation will result in fewer merge conflicts when multiple engineers will work on validation.

2024-09-12 18:03 UTC, brentschmaltz requested changes
Please split into PR's focusing on one validation step.

2024-09-13 14:39 UTC, iNinja commented
Closing the PR, will re-raise individual ones as I add more tests.

2024-09-13 14:39 UTC, closed without merging