Replace JsonWebToken read overload method with delegates to read token values.
AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet pull request #2981
Opened 2024-11-05 18:01 UTC by pmaytak

2024-11-07 20:35 UTC, pmaytak commented
**Edit: These results are outdated.**

Looks like when using delegates there're extra allocations because of:
```csharp
string claimName = reader.GetString();
claims[claimName] = ReadTokenPayloadValueDelegate(ref reader, claimName);
```

|Delegates| Method                                        | Mean     | Ratio | Error    | StdDev   | P90      | P95      | P100     | Gen0   | Allocated | Alloc Ratio |
|--|---------------------------------------------- |---------:|---------:|---------:|---------:|---------:|---------:|------:|-------:|----------:|------------:|
|Without| JsonWebTokenHandler_ValidateTokenAsyncWithTVP | 30.72 μs |  1.000 | 0.026 μs | 0.055 μs | 30.79 μs | 30.81 μs | 30.89 μs | 0.2441 |   7.23 KB |        1.00 |
|With| JsonWebTokenHandler_ValidateTokenAsyncWithTVP | 30.66 μs |  0.998 | 0.124 μs | 0.273 μs | 30.96 μs | 31.02 μs | 31.10 μs | 0.3052 |   7.55 KB |        1.044 |

|Delegates| Method             | Mean     |Ratio | Error     | StdDev    | P90      | P95      | P100     | Gen0   | Allocated |Alloc Ratio|
|--|------------------- |---------:|----------:|--:|----------:|---------:|---------:|---------:|-------:|----------:|--:|
|Without| ReadJWS_FromMemory | 8.373 μs |1.00| 0.0331 μs | 0.0727 μs | 8.465 μs | 8.499 μs | 8.530 μs | 0.2289 |   5.84 KB | 1.00|
|With| ReadJWS_FromMemory | 8.201 μs |0.979| 0.0287 μs | 0.0636 μs | 8.295 μs | 8.313 μs | 8.357 μs | 0.2441 |   6.07 KB | 1.039 |

2025-01-15 08:20 UTC, pmaytak commented
Updated results comparing delegates which have a dictionary as a parameter.

|Delegates| Method                                        | Mean     | Ratio | Error    | StdDev   | P90      | P95      | P100     | Ratio | Gen0   | Allocated | Alloc Ratio |
|-:|---------------------------------------------- |---------:|---------:|--:|---------:|---------:|---------:|---------:|------:|-------:|----------:|------------:|
|Without| JsonWebTokenHandler_ValidateTokenAsyncWithTVP | 30.13 μs | 1.00 | 0.169 μs | 0.374 μs | 30.61 μs | 30.74 μs | 31.07 μs |  1.00 | 0.2441 |   7.23 KB |        1.00 |
|With| JsonWebTokenHandler_ValidateTokenAsyncWithTVP | 30.22 μs | 1.00 | 0.315 μs | 0.679 μs | 31.14 μs | 31.48 μs | 33.30 μs |  1.00 | 0.3052 |   7.55 KB |        1.044 |

|Delegates| Method             | Mean     | Ratio | Error     | StdDev    | P90      | P95      | P100     | Gen0   | Allocated | Alloc Ratio |
|--:|------------------- |---------:|----------:|--: |----------:|---------:|---------:|---------:|-------:|----------:|--:|
|Without| ReadJWS_FromMemory | 7.523 μs | 1.00 | 0.0333 μs | 0.0724 μs | 7.599 μs | 7.612 μs | 7.672 μs | 0.2365 |   5.84 KB | 1.00 |
|With | ReadJWS_FromMemory | 7.370 μs | 0.980 |0.0182 μs | 0.0392 μs | 7.422 μs | 7.432 μs | 7.453 μs | 0.2441 |   6.06 KB | 1.038 |

BenchmarkDotNet v0.13.12, Windows 11 (10.0.26100.2605) (Hyper-V)
Intel Xeon Platinum 8370C CPU 2.80GHz, 1 CPU, 16 logical and 8 physical cores
.NET SDK 9.0.101
  [Host]    : .NET 8.0.11 (8.0.1124.51707), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
  MediumRun : .NET 8.0.11 (8.0.1124.51707), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI

2025-02-18 18:56 UTC, brentschmaltz commented on src/Microsoft.IdentityModel.JsonWebTokens/Json/JsonWebToken.PayloadClaimSet.cs
> +                    else if (reader.ValueTextEquals(JwtPayloadUtf8Bytes.Azp))
The user will have no ability to parse any of the claims that are parsed before calling the delegate.

2025-02-18 19:01 UTC, brentschmaltz commented
It would be great to have the same design when reading the header.

2025-02-18 19:05 UTC, brentschmaltz requested changes
We need a way to allow the user to parse all claims in a performant manner.
This design skips claims that are parsed.

Allowing the user to parse all claims allows for an implementation where validation could fail fast.

Failing fast needs to have a design that can propagate a detailed error result to upper layers for error reporting.

2025-03-24 06:49 UTC, pmaytak commented
The three scenarios compared below:
- Dev branch, JWT has custom claims, these are saved as string JSON.
- This feature branch, JWT has custom claims, no delegates are set, claims are saved as strings.
- This feature branch, JWT has custom claims and delegates which parse them into an object.
- Same cases as above, also creates claims.

| Branch  | Method                                                           | Mean     | Ratio | Error    | StdDev   | P90      | P95      | P100     | Gen0   | Allocated | Alloc Ratio |
|---------|------------------------------------------------------------------|----------|-------|----------|----------|----------|----------|----------|--------|-----------|-------------|
| Base    | JsonWebTokenHandler_ValidateTokenAsync                           | 30.59 μs | **1.000**  | 0.037 μs | 0.079 μs | 30.68 μs | 30.72 μs | 30.85 μs | 0.4272 | 7.51 KB   | **1.000**        |
| Feature | JsonWebTokenHandler_ValidateTokenAsync                           | 31.27 μs | **1.022** | 0.322 μs | 0.672 μs | 32.30 μs | 32.40 μs | 32.61 μs | 0.4272 | 7.94 KB   | **1.057**        |
| Feature | JsonWebTokenHandler_ValidateTokenAsyncWithDelegates              | 31.47 μs | **1.029**  | 0.110 μs | 0.242 μs | 31.79 μs | 31.87 μs | 32.03 μs | 0.4883 | 8 KB      | **1.065**        |
| Base    | JsonWebTokenHandler_ValidateTokenAsync_CreateClaims              | 35.38 μs | **1.000**  | 0.130 μs | 0.286 μs | 35.80 μs | 35.88 μs | 36.10 μs | 1.0376 | 17.3 KB   | **1.000**        |
| Feature | JsonWebTokenHandler_ValidateTokenAsync_CreateClaims              | 35.20 μs | **0.995** | 0.057 μs | 0.121 μs | 35.33 μs | 35.36 μs | 35.43 μs | 1.0376 | 17.73 KB  | **1.025**        |
| Feature | JsonWebTokenHandler_ValidateTokenAsyncWithDelegates_CreateClaims | 35.64 μs | **1.007**  | 0.069 μs | 0.151 μs | 35.84 μs | 35.86 μs | 36.00 μs | 1.0376 | 17.79 KB  | **1.028**       |

2025-03-24 18:45 UTC, pmaytak commented
The three scenarios compared below:
- Dev branch, JWT has custom claims, these are saved as string JSON.
- This feature branch, JWT has custom claims, no delegates are set, claims are saved as strings.
- This feature branch, JWT has custom claims and delegates which parse them into an object.
- Same cases as above, also creates claims.

| Branch  | Method                                                           | Mean     | Ratio | Error    | StdDev   | P90      | P95      | P100     | Gen0   | Allocated | Alloc Ratio |
|---------|------------------------------------------------------------------|----------|-------|----------|----------|----------|----------|----------|--------|-----------|-------------|
| Base    | JsonWebTokenHandler_ValidateTokenAsync                           | 30.59 μs | **1.000**  | 0.037 μs | 0.079 μs | 30.68 μs | 30.72 μs | 30.85 μs | 0.4272 | 7.51 KB   | **1.000**        |
| Feature | JsonWebTokenHandler_ValidateTokenAsync                           | 30.29 μs | **0.990** | 0.061 μs | 0.131 μs | 30.47 μs | 30.51 μs | 30.65 μs | 0.4272 | 7.63 KB   | **1.016**        |
| Feature | JsonWebTokenHandler_ValidateTokenAsyncWithDelegates              | 31.16 μs | **1.019** | 0.099 μs | 0.217 μs | 31.51 μs | 31.54 μs | 31.59 μs | 0.4272 | 7.77 KB   | **1.035**        |
| Base    | JsonWebTokenHandler_ValidateTokenAsync_CreateClaims              | 35.38 μs | **1.000**  | 0.130 μs | 0.286 μs | 35.80 μs | 35.88 μs | 36.10 μs | 1.0376 | 17.3 KB   | **1.000**        |
| Feature | JsonWebTokenHandler_ValidateTokenAsync_CreateClaims              | 34.65 μs | **0.979**  | 0.074 μs | 0.162 μs | 34.84 μs | 34.93 μs | 35.03 μs | 0.9766 | 17.41 KB  | **1.006**        |
| Feature | JsonWebTokenHandler_ValidateTokenAsyncWithDelegates_CreateClaims | 35.70 μs | **1.009**  | 0.083 μs | 0.180 μs | 35.86 μs | 35.96 μs | 36.47 μs | 1.0376 | 17.55 KB  | **1.008**        |

2025-04-09 03:49 UTC, pmaytak commented
The difference from the previous commit is that there's now one delegate instead of a dictionary.

The three scenarios compared below:
- Dev branch, JWT has custom claims, these are saved as string JSON.
- This feature branch, JWT has custom claims, no delegates are set, claims are saved as strings.
- This feature branch, JWT has custom claims and delegates which parse them into an object.
- Same cases as above, also creates claims.

| Branch  | Method                                                           | Mean     | Ratio | Error    | StdDev   | P90      | P95      | P100     | Gen0   | Allocated | Alloc Ratio |
|---------|------------------------------------------------------------------|----------|-------|----------|----------|----------|----------|----------|--------|-----------|-------------|
| Base    | JsonWebTokenHandler_ValidateTokenAsync                           | 30.59 μs | **1.000**  | 0.037 μs | 0.079 μs | 30.68 μs | 30.72 μs | 30.85 μs | 0.4272 | 7.51 KB   | **1.000**        |
| Feature | JsonWebTokenHandler_ValidateTokenAsync                           | 30.56 μs |  **1.000**  | 0.055 μs | 0.120 μs | 30.71 μs | 30.73 μs | 30.87 μs | 0.4272 |   7.61 KB |  **1.013** |
| Feature | JsonWebTokenHandler_ValidateTokenAsyncWithDelegates              | 31.08 μs | **1.016**  | 0.075 μs | 0.166 μs | 31.30 μs | 31.33 μs | 31.53 μs  | 0.4272 |   7.75 KB | **1.032**  |
| Base    | JsonWebTokenHandler_ValidateTokenAsync_CreateClaims              | 35.38 μs | **1.000**  | 0.130 μs | 0.286 μs | 35.80 μs | 35.88 μs | 36.10 μs | 1.0376 | 17.3 KB   | **1.000**        |
| Feature | JsonWebTokenHandler_ValidateTokenAsync_CreateClaims              | 35.34 μs | **0.999**  | 0.087 μs | 0.189 μs | 35.54 μs | 35.61 μs | 35.81 μs | 0.9766 |   17.4 KB | **1.006**  |
| Feature | JsonWebTokenHandler_ValidateTokenAsyncWithDelegates_CreateClaims | 35.25 μs | **0.996**  | 0.072 μs | 0.159 μs | 35.47 μs | 35.49 μs | 35.59 μs | 1.0376 |  17.54 KB | **1.014**  |

2025-04-10 22:11 UTC, keegan-caruso commented on src/Microsoft.IdentityModel.JsonWebTokens/JsonWebToken.cs
> +        /// object ReadPayloadValueDelegate(ref Utf8JsonReader reader) =&gt;
Does this need updated?

2025-04-11 01:42 UTC, brentschmaltz commented on src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs
> +        public TryReadJwtClaim TryReadJwtClaim { get; set; }
The reader will need to know if the runtime is considering the Header or Payload.
Couple of ideas, we can have two delegates one for each, OR we can pass a parameter.

Passing a parameter would work better with SAML tokens that have three statements by default which would lead to three delegates.

2025-04-14 03:41 UTC, pmaytak commented
| Branch  | Method                                                           | Mean     | Ratio | Error    | StdDev   | P90      | P95      | P100     | Gen0   | Allocated | Alloc Ratio |
|---------|------------------------------------------------------------------|----------|-------|----------|----------|----------|----------|----------|--------|-----------|-------------|
| Base    | JsonWebTokenHandler_ValidateTokenAsync                           | 30.59 μs | **1.000**  | 0.037 μs | 0.079 μs | 30.68 μs | 30.72 μs | 30.85 μs | 0.4272 | 7.51 KB   | **1.000**        |
| Feature | JsonWebTokenHandler_ValidateTokenAsync                           | 30.53 μs |  **0.998**| 0.055 μs | 0.120 μs | 30.70 μs | 30.75 μs | 30.78 μs | 0.4272 |   7.61 KB | **1.013** |
| Feature | JsonWebTokenHandler_ValidateTokenAsyncWithDelegates              | 31.16 μs |  **1.019**| 0.073 μs | 0.160 μs | 31.33 μs | 31.42 μs | 31.63 μs | 0.4272 |   7.75 KB |  **1.032** |
| Base    | JsonWebTokenHandler_ValidateTokenAsync_CreateClaims              | 35.38 μs | **1.000**  | 0.130 μs | 0.286 μs | 35.80 μs | 35.88 μs | 36.10 μs | 1.0376 | 17.3 KB   | **1.000**        |
| Feature | JsonWebTokenHandler_ValidateTokenAsync_CreateClaims              | 34.84 μs |  **0.985**| 0.093 μs | 0.198 μs | 35.08 μs | 35.16 μs | 35.39 μs |  1.00 | 0.9766 |   17.4 KB | **1.006** |
| Feature | JsonWebTokenHandler_ValidateTokenAsyncWithDelegates_CreateClaims | 35.18 μs |  **0.994**| 0.086 μs | 0.190 μs | 35.40 μs | 35.43 μs | 35.58 μs |  1.01 | 1.0376 |  17.54 KB |  **1.014** |

2025-04-14 17:16 UTC, keegan-caruso commented on src/Microsoft.IdentityModel.Tokens/TokenEnums.cs
> +        Header,
```suggestion
        Header = 0,
```

2025-04-14 20:20 UTC, pmaytak commented on src/Microsoft.IdentityModel.Tokens/TokenEnums.cs
> +        Header,
Why? Isn't it 0 by default?

2025-04-17 14:24 UTC, brentschmaltz approved these changes

2025-04-17 20:59 UTC, pmaytak commented on src/Microsoft.IdentityModel.JsonWebTokens/Json/JsonClaimSet.cs
> +                claims.Add(new Claim(claimType, value.ToString(), ClaimValueTypes.String, issuer, issuer));
With the current code, when we read some unknown to IdentityModel claim, we cache it as a JSON string. With the new changes, the internal claims collection may now have custom classes and types other than what is checked above. So this makes sure these custom claims are added to ClaimsIdentity.

2025-04-17 21:01 UTC, keegan-caruso commented on src/Microsoft.IdentityModel.JsonWebTokens/Json/JsonWebToken.HeaderClaimSet.cs
> +                        claims[claimName] = JsonSerializerPrimitives.ReadPropertyValueAsObject(ref reader, claimName, JsonClaimSet.ClassName, false);
Can you comment on the class name here?

2025-04-17 21:06 UTC, keegan-caruso commented on src/Microsoft.IdentityModel.JsonWebTokens/JsonWebToken.cs
> +        internal TryReadJwtClaim TryReadJwtClaim { get; set; }
private set?

2025-04-17 21:09 UTC, keegan-caruso commented on src/Microsoft.IdentityModel.Tokens/TokenEnums.cs
> +        Header,
More explicit, but fair point.

2025-04-17 21:10 UTC, keegan-caruso approved these changes
Few small questions, but otherwise LGTM

2025-04-17 22:11 UTC, pmaytak commented on src/Microsoft.IdentityModel.JsonWebTokens/Json/JsonClaimSet.cs
> +                claims.Add(new Claim(claimType, value.ToString(), ClaimValueTypes.String, issuer, issuer));
Above we only add claims to claims identity for known types. So with new read code, if custom claim class is added, it won't be added to the ClaimsIdentity. This line makes sure it does get added as a string. 

The reason why this line wasn't needed before is because we would end up [reading the claims with unknown names as strings](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/faa4998627289e752124c0f5ceb6e0c4c453bc18/src/Microsoft.IdentityModel.Tokens/Json/JsonSerializerPrimitives.cs#L953).

2025-04-18 06:04 UTC, pmaytak commented on src/Microsoft.IdentityModel.JsonWebTokens/Json/JsonWebToken.HeaderClaimSet.cs
> +                        claims[claimName] = JsonSerializerPrimitives.ReadPropertyValueAsObject(ref reader, claimName, JsonClaimSet.ClassName, false);
This is from the existing code. It just ends up being used in logs: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/faa4998627289e752124c0f5ceb6e0c4c453bc18/src/Microsoft.IdentityModel.Tokens/Json/JsonSerializerPrimitives.cs#L41

2025-04-18 15:47 UTC, keegan-caruso approved these changes

2025-04-18 17:44 UTC, merged